### ISSUE TITLE
problem when interrogated by guard - do not have the opportunity to pacify.  

### ISSUE THREAD

**Issue by danpritts** [UnNetHack/UnNetHack#58]
I ran into a guard while I was in the vault with the portal.  I had already killed Croesus.

I gave the guard my name, but was unable to pacify him.  See attached screenshot. 

Can provide (macos x64) savefile & config.log, commit was:

```
commit a72806564aaeab8eec9a7f23807d8e0049c006b2 (HEAD -> master, origin/master, origin/HEAD)
Author: Patric Mueller <bhaak@gmx.net>
Date:   Fri Jan 27 13:27:18 2023 +0100
```

**Comment by danpritts** [comment]
<img width="833" alt="weirdness with guard" src="https://user-images.githubusercontent.com/1068849/229870156-b07eed62-8888-44d9-8113-5b30a75ddb57.png">

**Comment by bhaak** [comment]
This usually means that you have gold stacked away in a sack or another container.

The guards are pretty strict and consider any gold that you carry as belonging to the vault.

I did notice though that your communication with the guard is missing sentences. The guard didn't give you the introduction warning. This will be fixed shortly. I also think a last warning would be nice so that you get another turn to drop any gold before the guard attacks you.
